services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sigm
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sigm.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"